DoList/dolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

DoList/main/urls.py
from django.urls import path
from .views import TastkList, TaskDetail, TaskCreate, TaskUpdate, TaskDelite, CustomLoginView, RegisterPage
from django.contrib.auth.views import LogoutView

app_name = 'main'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='main:login'), name='logout'),
    path('register/', RegisterPage.as_view(), name='register'),
    path('', TastkList.as_view(), name='tasks'),
    path('task/<int:pk>/', TaskDetail.as_view(), name='task'),
    path('task-create/', TaskCreate.as_view(), name='task-create'),
    path('task-update/<int:pk>/', TaskUpdate.as_view(), name='task-update'),
    path('task-delete/<int:pk>/', TaskDelite.as_view(), name='task-delete'),
]

DoList/main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Task(models.Model):
    class Meta:
        ordering = ['complite']

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    complite = models.BooleanField(default=False)
    create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

DoList/main/views.py
from django.shortcuts import render, redirect
from .models import Task
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login


class CustomLoginView(LoginView):
    template_name = 'main/login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('main:tasks')


class RegisterPage(FormView):
    template_name = 'main/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('main:tasks')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('tasks')
        return super(RegisterPage, self).get(*args, **kwargs)


class TastkList(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = 'tasks'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = context['tasks'].filter(user=self.request.user)
        context['count'] = context['tasks'].filter(complite=False).count()

        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['tasks'] = context['tasks'].filter(
                title__startswith=search_input)

        context['search_input'] = search_input

        return context


class TaskDetail(LoginRequiredMixin, DetailView):
    model = Task
    context_object_name = 'task'
    template_name = 'main/task.html'


class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    fields = ['title', 'description', 'complite']
    success_url = reverse_lazy('main:tasks')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TaskCreate, self).form_valid(form)


class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ['title', 'description', 'complite']
    success_url = reverse_lazy('main:tasks')


class TaskDelite(LoginRequiredMixin, DeleteView):
    model = Task
    context_object_name = 'task'
    success_url = reverse_lazy('main:tasks')

DoList/main/templates/main/login.html
{% extends 'main/main.html' %} {% block content %}

<div class="header-bar">
  <h1>Login</h1>
</div>

<div class="card-body">
  <form method="POST">
    {% csrf_token %} {{form.as_p}}
    <input class="button" type="submit" value="Login" />
  </form>
  <p>Don't have an account?<a href="{% url 'main:register' %}">Register</a></p>
</div>

{% endblock content %}

DoList/main/templates/main/main.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@200&display=swap"
      rel="stylesheet"
    />
    <title>To Do List</title>
    <style>
      body {
        background-color: #fafafa;
        font-family: "Nunito Sans", sans-serif;
        padding-top: 50px;
      }
      h1,
      h2,
      h3,
      h4,
      h5,
      h6 {
        font-family: "Raleway", sans-serif;
      }

      a,
      p {
        color: #4b5156;
      }

      .container {
        max-width: 550px;
        margin: auto;
        background-color: #fff;
        -webkit-box-shadow: 2px 2px 13px -4px rgba(0, 0, 0, 0.21);
        box-shadow: 2px 2px 13px -4px rgba(0, 0, 0, 0.21);
      }

      .header-bar {
        display: flex;
        justify-content: space-between;
        color: #fff;
        padding: 10px;
        border-radius: 5px 5px 0 0;
        background: linear-gradient(
          90deg,
          #eea390 0%,
          #eb796f 43%,
          #eb796f 100%
        );
      }

      .header-bar a {
        color: rgb(247, 247, 247);
        text-decoration: none;
      }

      .task-wrapper {
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 20px;
        background-color: #fff;
        border-top: 1px solid rgb(226, 226, 226);
      }

      .task-title {
        display: flex;
      }

      .task-title a {
        text-decoration: none;
        color: #4b5156;
        margin-left: 10px;
      }

      .task-complete-icon {
        height: 20px;
        width: 20px;
        background-color: rgb(105, 192, 105);
        border-radius: 50%;
      }
      .task-incomplete-icon {
        height: 20px;
        width: 20px;
        background-color: rgb(209, 218, 218);
        border-radius: 50%;
      }

      .delete-link {
        text-decoration: none;
        font-weight: 900;
        color: #cf4949;
        font-size: 20px;
        line-height: 0;
      }

      #search-add-wrapper {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 10px;
      }

      #add-link {
        color: #eb796f;
        text-decoration: none;
        font-size: 42px;
        text-shadow: 1px 1px #81413b;
      }

      input[type="text"],
      input[type="password"],
      textarea {
        border: 1px solid #eb796f;
        border-radius: 5px;
        padding: 10px;
        width: 90%;
      }

      label {
        padding-top: 10px !important;
        display: block;
      }
      .button {
        border: 1px solid #e8796f;
        background-color: #fafafa;
        color: #eb796f;
        padding: 10px;
        font-size: 14px;
        border-radius: 5px;
        cursor: pointer;
        text-decoration: none;
      }
      .card-body {
        padding: 20px;
      }
    </style>
  </head>
  <body>
    <div class="container">{% block content %} {% endblock content %}</div>
  </body>
</html>

DoList/main/templates/main/register.html
{% extends 'main/main.html' %} {% block content %}
<div class="header-bar">
  <h1>Register</h1>
</div>
<div class="card-body">
  <form method="POST">
    {% csrf_token %}
    <label> {{form.username.label}}</label>
    {{form.username}}
    <label> {{form.password1.label}}</label>
    {{form.password1}}
    <label> {{form.password2.label}}</label>
    {{form.password2}}
    <input
      style="margin-top: 10px"
      class="button"
      type="submit"
      value="Register"
    />
  </form>

  <p>lready have an account?<a href="{% url 'main:login' %}">Login</a></p>
</div>
{% endblock content %}

DoList/main/templates/main/task.html
{% extends 'main/main.html' %} {% block content %}

<h1>Task: {{task}}</h1>
{% endblock content %}

DoList/main/templates/main/task_confirm_delete.html
{% extends 'main/main.html' %} {% block content %}

<div class="header-bar">
  <a href="{% url 'main:tasks' %}">&#8592; Back</a>
</div>
<div class="card-body">
  <form method="POST" action="">
    {% csrf_token %}
    <p>Are your sure you wont to delete this task? "{{task}}</p>
    <input class="button" type="submit" value="Delete" />
  </form>
</div>

{% endblock content %}

DoList/main/templates/main/task_form.html
{% extends 'main/main.html' %} {% block content %}

<div class="header-bar">
  <a href="{% url 'main:tasks' %}">&#8592; Back</a>
</div>

<div class="card-body">
  <form method="POST" action="">
    {% csrf_token %} {{form.as_p}}
    <input
      class="button"
      type="submit"
      name="submit"
      id="submit"
      value="Submit"
    />
  </form>
</div>
{% endblock content %}

DoList/main/templates/main/task_list.html
{% extends 'main/main.html' %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  {% block content %}
  <body>
    <div class="header-bar">
      <div>
        <h1>Welcome {{request.user|capfirst }}</h1>
        <h3 style="margin: 0">
          You have <i>{{count}}</i> incomplete task{{ count|pluralize:'s' }}
        </h3>
      </div>
      {% if request.user.is_authenticated %}
      <a href="{% url 'main:logout' %}">Logout</a>
      {% else %}
      <a href=" {% url 'main:login' %}">Login</a>
      {% endif %}
    </div>

    <div id="search-add-wrapper">
      <form method="GET" style="margin-top: 20px; display: flex">
        <input type="text" name="search-area" value="{{search_input}}" />
        <input class="button" type="submit" value="Search" />
      </form>
      <a id="add-link" href="{% url 'main:task-create' %}">&#x2b;</a>
    </div>

    <div class="task-items-wrapper">
      {% for task in tasks %}
      <div class="task-wrapper">
        {% if task.complete %}
        <div class="task-title">
          <div class="task-complete-icon"></div>
          <i>
            <s><a href="{% url 'main:task-update' task.id %}">{{task}}</a></s>
          </i>
        </div>
        {% else %}
        <div class="task-title">
          <div class="task-incomplete-icon"></div>
          <a href="{% url 'main:task-update' task.id %}">{{task}}</a>
        </div>
        <a class="delete-link" href="{% url 'main:task-delete' task.id %}"
          >&#215;</a
        >
        {% endif %}
      </div>
      {% empty %}
      <h3>No item in list</h3>
      {% endfor %}
    </div>
  </body>
  {% endblock content %}
</html>